name: grocery_glide
description: "A simple and efficient grocery list manager.
 Features:
 Master template management,
 Monthly grocery lists,
 Shopping progress tracking,
 Search and filter capabilities."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  http: ^1.6.0
  shorebird_code_push: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
